version: "3.8"
services:
    back-end:
        container_name: back-end
        build:
            target: base
        volumes:
            - ./:/usr/src/app
        ports:
            - "3200:3000"
        env_file: .env
        command: npm run start:dev
        depends_on:
            db:
                condition: service_started
        networks:
            - back-end
    db:
        container_name: db
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "example"
            MYSQL_DATABASE: back-end
        ports:
            - 3307:3306
        volumes:
            - dbmysql:/var/lib/mysql
        networks:
            - back-end

networks:
    back-end:
        driver: bridge
        name: back-end

volumes:
    dbmysql:
        driver: "local"
